### ISSUE TITLE
Add Sphinx Installation Instructions for Homebrew

### ISSUE THREAD

**Issue by martinvelez** [kodethon/Docs#2]
How did you successfully installed Sphinx on a Mac using Homebrew?

Please add insructions to README.md.

## Rough Instructions.

Get the latest changes.
```
cd github/kodethon/Docs
git pull
```

Edit README.md.  Commit and push your changes.
```
git add README.md
git commit -m 'Added Sphinx installation instructions for Homebrew.'
git push
```

**Comment by bakelly18** [comment]
I ended up having to install MacPorts because pip wouldn't work correctly with Homebrew and it was easier to work with.
